language: php

php:
	- 5.3.3
	- 5.4

env:
  - DB=sqlite

services:
  - redis-server

before_script:
  - composer install --no-interaction --quiet

script: php tests/lint.php src/Kdyby/ tests/KdybyTests/ && VERBOSE=true ./tests/run-tests.sh -s tests/
